#!/usr/bin/perl -w

# sudo sysctl -w net.ipv4.ip_forward=1

use strict;
use Cwd;
my $dir = getcwd;
$ENV{'dir'} = $dir;

# run stationary experiments
system '$dir/run-verus-stat';
system '$dir/run-sprout-stat';
system '$dir/run-cubic-stat';
system '$dir/run-reno-stat';

#run AT&T stats
system '$dir/run-verus-att';
system '$dir/run-sprout-att';
system '$dir/run-cubic-att';
system '$dir/run-reno-att';



# create plots

# stationary
# system 'mm-throughput-graph 5 $dir/logs/sprout_stat_log.down > $dir/plots/sprout_stat_tput.html'

# system 'mm-tput-dual-graph 500 $dir/logs/verus6_verizon_log $dir/logs/sprout_verizon_log > $dir/plots/sprout_verus_verizon_tput.html';
# system 'mm-tput-delay-graph 500 $dir/logs/sprout_verizon_log $dir/logs/verus2_verizon_log $dir/logs/verus4_verizon_log $dir/logs/verus6_verizon_log > $dir/plots/sprout_verus_verizon_tput_delay.html';
